### PR TITLE
Updated read me to point to tinker for examples. (bunq/sdk_java#81)

### PR DESCRIPTION
**Pull request by OGKevin**
References #81

### CODE REVIEW

**Comment by OGKevin** [comment]
@patrickdw1991 please 👓

**Comment by patrickdw1991** [comment]
The links you use aren't really nice, the problem would be that if you update the tinker repo you might also need to update the readme to fix the links (and point them to the newer versions of the example files)

**Comment by OGKevin** [comment]
@patrickdw1991 yes that is intended, as if tinker changes and the code line shifts ore something these links must be updated. Its is better to link to something good as of the user landing on random lines in tinker that has nothing to do with the example :P.

**Comment by OGKevin** [comment]
@andrederoos

**Pull request merged**
